### ISSUE TITLE
Unexpected pronunciations

### ISSUE THREAD

**Issue by acx2015** [mrzarquon/portland#10]
> Couch is pronounced "cooch" and Oregon is "orygun"

You forgot a few:
- Glisan: "GLEE-son" not "GLISS-on"
- Kearney: "KURN-ee" not "KEER-nee"
- Going: "GOYNG" (one syllable, like "boing") not "GOH-ing"
- Savier: "SAYvior" not "suh-VEER" or "SAHV-yer" or "suh-VYER"

And my favorite:
- Willamette: rhymes with "Dammit"

**Comment by mrzarquon** [comment]
Feel free to send a PR with those changes, thats more than a quick hack to get done if you want to add a "pronunciations" section

**Comment by mckern** [comment]
Hey @mwaggett could I persuade you to help out with this? There's not going to be a PR pending from the original issue submitted, and you're qualified. Many pleases, many thanks.

**Comment by mwaggett** [comment]
can do!
