### ISSUE TITLE
Hailing cabs

### ISSUE THREAD

**Issue by acx2015** [mrzarquon/portland#11]
> Cabs have to dispatched, you can't hail them.

Except at the airport and train station anytime (Amtrak, not MAX), and downtown on weekend nights if you're in the right place at the right time.

In fact, weekend nights they line up outside popular Chinatown clubs waiting to take drunks home without a phone call.

**Comment by mrzarquon** [comment]
True, updated. However you still can't hail a cab in town unless you get a bored cabbie.
