### ISSUE TITLE
Where does one purchase a certain plant? 

### ISSUE THREAD

**Issue by stahnma** [mrzarquon/portland#2]
I've heard that people coming to PDX are really into botany, and there are plants in special shops or something.

**Comment by call** [comment]
You won't have to go even a full block.

http://ofmeds.com/2015/08/19/oregons-finest-is-growing-we-are-hiring/

**Comment by stahnma** [comment]
Oh, I didn't want/need any. I just assumed it would be an FAQ.

**Comment by call** [comment]
Not a personal recommendation, Mike, just an observation from the OCC walk through. It's incredibly prominent across MLK. Also, it's federally legal to window shop.

**Comment by mrzarquon** [comment]
FAQ section added and link to WWeek's Potlander guide added.
