### ISSUE TITLE
Pandemic 2020

### ISSUE THREAD

**Issue by mckern** [mrzarquon/portland#59]
This should probably get updated now that @mrzarquon has abandoned town and so much has had to adjust/close thanks to the pandemic.

**Comment by mrzarquon** [comment]
hey @mckern should I transfer this repo to you if you're up for taking it over? I can work on a belfast one next year.

**Comment by mckern** [comment]
yeah, that's probably not a bad idea. gimme, and I'll update it since it's been a fucking apocalypse here.
